--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-3.pgdg22.04+1)
-- Dumped by pg_dump version 16.2

-- Started on 2025-09-26 20:06:52 CEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4003 (class 0 OID 54916003)
-- Dependencies: 220
-- Data for Name: property; Type: TABLE DATA; Schema: spatial_metadata; Owner: sis
--

INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PEAT', 'Peat', 'class', 0, 1, 'Carbon (C) - organic', 'categorical', 4, '#CA0020', '#3F68E2', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGS', 'Carbon (C) - organic stock', 't/(ha·a)', 5.227511, 878.3219, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRSSM2', 'GSOCseq - absolute sequestration rate sustainable soil managemen 2', 't/(ha·a)', -4.998517e+22, 3.4309466e+10, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CLAY', 'Clay texture fraction', '%', 2.0954218, 67.95525, 'Clay texture fraction', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",clay,texture}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORG', 'Carbon (C) - organic', '%', 0.102681465, 76.38958, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCSSM1', 'GSOCseq - final SOC stocks after 20 years - sustainable soil managemen 1', 't/(ha·a)', -788.0185, 9847.136, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRSRSSM3', 'GSOCseq - relative sequestration rate sustainable soil managemen 3', 't/(ha·a)', -64.949585, 4.6507387e+23, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRSRSSM2', 'GSOCseq - relative sequestration rate sustainable soil managemen 2', 't/(ha·a)', -64.949585, 4.781821e+23, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NAEXC', 'Sodium (Na+) - exchangeable', 'cmol/kg', 0.009701022, 107.95939, 'Sodium (Na+) - exchangeable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SALT', 'Salinification', 'class', 1, 11, 'Sodium (Na+) - exchangeable', 'categorical', 4, '#CA0020', '#3F68E2', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRDSSM1', 'GSOCseq - relative difference sustainable soil managemen 1', 't/(ha·a)', -1298.9917, 1282.3726, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCSSM2', 'GSOCseq - final SOC stocks after 20 years - sustainable soil managemen 2', 't/(ha·a)', -788.0185, 9847.136, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRBAU', 'GSOCseq - absolute sequestration rate business-as-usual', 't/(ha·a)', -4.998517e+22, 3.8285484e+18, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADSSM1', 'GSOCseq - absolute difference sustainable soil managemen 1', 't/(ha·a)', -9.9970335e+23, 279.31744, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SAND', 'Sand texture fraction', '%', 1.5986466, 81.790276, 'Sand texture fraction', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",sand,texture}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCBAU', 'GSOCseq - final SOC stocks after 20 years - business-as-usual', 't/(ha·a)', -9.2452505e+22, 9.84116e+23, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADSSM3', 'GSOCseq - absolute difference sustainable soil managemen 3', 't/(ha·a)', -9.9970335e+23, 278.24826, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PXX', 'Phosphorus (P)', 'mg/kg', 1.18992, 414.6663, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGSOCSSM3', 'GSOCseq - final SOC stocks after 20 years - sustainable soil managemen 3', 't/(ha·a)', -788.0185, 9847.136, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGT0', 'GSOCseq - initial SOC stocks at year 2020 - time zero', 't/(ha·a)', -3.0578473e+10, 9.9970335e+23, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRSSM1', 'GSOCseq - absolute sequestration rate sustainable soil managemen 1', 't/(ha·a)', -4.998517e+22, 3.4309466e+10, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CEC', 'Cation exchange capacity', 'cmol/kg', 1.1099763, 69.35965, 'cationExchangeCapacitycSoilProperty', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","cation exchange capacity"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRDSSM2', 'GSOCseq - relative difference sustainable soil managemen 2', 't/(ha·a)', -1298.9917, 1293.8951, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BKD', 'Bulk density', 'kg/dm³', 0.017327346, 1.6802648, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","bulk density"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADSSM2', 'GSOCseq - absolute difference sustainable soil managemen 2', 't/(ha·a)', -9.9970335e+23, 274.29416, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGADBAU', 'GSOCseq - absolute difference business-as-usual', 't/(ha·a)', -9.9970335e+23, 270.34003, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRDSSM3', 'GSOCseq - relative difference sustainable soil managemen 3', 't/(ha·a)', -1298.9917, 1285.0342, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGASRSSM3', 'GSOCseq - absolute sequestration rate sustainable soil managemen 3', 't/(ha·a)', -4.998517e+22, 3.4309466e+10, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHX', 'pH - Hydrogen potential', 'pH', 0.17354426, 8.42964, 'pH - Hydrogen potential', 'quantitative', 10, '#CA0020', '#3F68E2', '{soil,"digital soil mapping",ph}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGRSRSSM1', 'GSOCseq - relative sequestration rate sustainable soil managemen 1', 't/(ha·a)', -64.949585, 4.8497784e+23, 'Carbon (C) - organic', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon,sequestration}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ACEXC', 'Acidity - exchangeable', 'cmol/kg', NULL, NULL, 'Acidity - exchangeable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",acidity}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CACO3ET', 'Calcium carbonate equivalent - total', 'g/kg', 0.0022378669, 9.722537, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CLSOL', 'Chloride (Cl-) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",chloride,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('KSOL', 'Potassium (K+) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NASOL', 'Sodium (Na+) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ACEXT', 'Acidity - extractable', 'cmol/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",acidity}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ALSAT', 'Aluminium (Al+++) - saturation (ESP)', '%', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",aluminium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BASAT', 'Base saturation', '%', 3.9748352, 310.83453, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","base saturation"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ALEXT', 'Aluminium (Al) - dithionite extractable', '%', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",aluminium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ALEXC', 'Aluminium (Al+++) - exchangeable', 'cmol/kg', NULL, NULL, 'Aluminium (Al+++) - exchangeable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",aluminium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BEXT', 'Boron (B) - extractable', '%', NULL, NULL, 'Boron (B) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",boron,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('AWCV', 'Available water capacity - volumetric', 'm³/100 m³', NULL, NULL, 'Available water capacity - volumetric (FC to WP)', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","water capacity"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BTOT', 'Boron (B) - total', '%', NULL, NULL, 'Boron (B) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",boron,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BREXT', 'Bromite (Br-) - extractable', 'mg/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",bromite,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BSATS', 'Base saturation - sum of cations', '%', 0.5860444, 21.523035, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","base saturation"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BSEXC', 'Bases - exchangeable', 'cmol/kg', 1.25032, 38.72092, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable bases"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('BSATC', 'Base saturation - calculated', '%', NULL, NULL, 'Base saturation - calculated', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","base saturation"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CAEXC', 'Calcium (Ca++) - exchangeable', 'cmol/kg', 0.64788485, 31.82854, 'Calcium (Ca++) - exchangeable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CATOT', 'Calcium (Ca++) - total', 'cmol/kg', NULL, NULL, 'Calcium (Ca++) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CAEXT', 'Calcium (Ca++) - extractable', 'cmol/kg', NULL, NULL, 'Calcium (Ca++) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CEXT', 'Carbon (C) - extractable', '%', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CASOL', 'Calcium (Ca++) - soluble', 'cmol/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CFA', 'Carbon (C) - fulvic acid', 'g/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CACO3EF', 'Calcium carbonate equivalent - fraction', 'g/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CFRAG', 'Coarse fragments', '%', NULL, NULL, 'coarseFragmentsProperty', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","coarse fragments"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CFRAGF', 'Coarse fragments - field class', '%', 6.5923385e-05, 47.75318, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","coarse fragments"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CLAWRB', 'World reference base', 'class', 1, 7, NULL, 'categorical', 7, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","soil classification",wrb}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CHA', 'Carbon (C) - humic acid', 'g/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CNRAT', 'Carbon/Nitrogen (C/N) ratio', 'dimensionless', 1.165, 129.77734, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",carbon,nitrogen}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CO3SOL', 'Carbonate (CO3--) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",calcium}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CORGNTOTR', 'Organic carbon (C) nitrogen (N) ratio', 'dimensionless', 5.91756, 53.81236, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",carbon,nitrogen}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CTHUM', 'Carbon (C) - total humic', 'g/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CTOT', 'Carbon (C) - total', 'g/kg', NULL, NULL, 'Carbon (C) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","organic carbon",carbon}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ECX', 'Electrical conductivity', 'dS/m', 0.00038286045, 24.637386, 'electricalConductivityProperty', 'quantitative', 10, '#CA0020', '#3F68E2', '{soil,"digital soil mapping","electrical conductivity"}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CUEXT', 'Copper (Cu) - extractable', '%', NULL, NULL, 'Copper (Cu) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",copper,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('CUTOT', 'Copper (Cu) - total', '%', NULL, NULL, 'Copper (Cu) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",copper,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('FEEXT', 'Iron (Fe) - extractable', '%', NULL, NULL, 'Iron (Fe) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",iron,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('FETOT', 'Iron (Fe) - total', '%', NULL, NULL, 'Iron (Fe) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",iron,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('HCO3SOL', 'Hydrocarbonate (HCO3-) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', NULL);
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('HEXC', 'Hydrogen (H+) - exchangeable', 'cmol/kg', NULL, NULL, 'Hydrogen (H+) - exchangeable', 'quantitative', 10, '#F4E7D3', '#5C4033', NULL);
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('KEXC', 'Potassium (K+) - exchangeable', 'cmol/kg', 0.23427553, 478.14163, 'Potassium (K+) - exchangeable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('KTOT', 'Potassium (K) - total', '%', 0.14559056, 2.4445798, 'Potassium (K) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('KEXT', 'Potassium (K) - extractable', 'cmol/kg', 15.2988205, 1249.2526, 'Potassium (K) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('KXX', 'Potassium (K)', 'mg/kg', 0.16248894, 756.61646, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",potassium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MGEXT', 'Magnesium (Mg) - extractable', 'cmol/kg', NULL, NULL, 'Magnesium (Mg) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",magnesium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MGEXC', 'Magnesium (Mg++) - exchangeable', 'cmol/kg', 0.1713, 7.6219, 'Magnesium (Mg++) - exchangeable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",magnesium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MGSOL', 'Magnesium (Mg++) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",magnesium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MGTOT', 'Magnesium (Mg) - total', 'cmol/kg', NULL, NULL, 'Magnesium (Mg) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",magnesium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MNEXT', 'Manganese (Mn) - extractable', 'cmol/kg', NULL, NULL, 'Manganese (Mn) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",manganese,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('MNTOT', 'Manganese (Mn) - total', 'cmol/kg', NULL, NULL, 'Manganese (Mn) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",manganese,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NAEXT', 'Sodium (Na) - extractable', 'cmol/kg', NULL, NULL, 'Sodium (Na) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NTOT', 'Nitrogen (N) - total', '%', 0.023296468, 37738.81, 'Nitrogen (N) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",nitrogen,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NATOT', 'Sodium (Na) - total', 'cmol/kg', NULL, NULL, 'Sodium (Na) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping","exchangeable sodium",salinity}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NO3SOL', 'Nitrate (NO3-) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",nitrogen,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('NO2SOL', 'Nitrite (NO2-) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",nitrogen,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PO4SOL', 'Phosphate (PO4--) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PRET', 'Phosphorus (P) - retention', 'g/hg', NULL, NULL, 'Phosphorus (P) - retention', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PHAQ', 'pH - Hydrogen potential in water', 'pH', 0.2249676, 7.75526, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",pH}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PEXT', 'Phosphorus (P) - extractable', '%', 13.796324, 336.86963, 'Phosphorus (P) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('PTOT', 'Phosphorus (P) - total', '%', 0.023891324, 1.083517, 'Phosphorus (P) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",phosphorus,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SEEXT', 'Selenium (Se) - extractable', 'mg/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",selenium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SETOT', 'Selenium (Se) - total', 'mg/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",selenium,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SEXT', 'Sulfur (S) - extractable', '%', NULL, NULL, 'Sulfur (S) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",sulfur,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SIEXT', 'Silicon (Si) - oxalate extractable', 'mg/kg', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",silicon,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SILT', 'Silt texture fraction', '%', 2.4598305, 76.15516, 'Silt texture fraction', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",silt,texture}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('SO4SOL', 'Sulfate (SO4--) - soluble', 'cmol/L', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",sulfur,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('STOT', 'Sulfur (S) - total', '%', NULL, NULL, 'Sulfur (S) - total', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",sulfur,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ZNEXT', 'Zinc (Zn) - extractable', '%', NULL, NULL, 'Zinc (Zn) - extractable', 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",zinc,nutrient}');
INSERT INTO spatial_metadata.property (property_id, name, unit_of_measure_id, min, max, property_phys_chem_id, property_type, num_intervals, start_color, end_color, keyword_theme) VALUES ('ZNTOT', 'Zinc (Zn) - total', '%', NULL, NULL, NULL, 'quantitative', 10, '#F4E7D3', '#5C4033', '{soil,"digital soil mapping",zinc,nutrient}');


-- Completed on 2025-09-26 20:06:52 CEST

--
-- PostgreSQL database dump complete
--

